version: "2"

services:
    admin:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: .env
        environment:
            CALLBACK_URL: "http://localhost:8090/login-callback"
            CLIENT_ID: "http://okami.funabashi.co.uk"
            SESSION_BUCKET: "admin.funabashi.co.uk"
        ports:
            - 8090:80

    mpserver:
        build:
            context: ./mocks/mpserver
        ports:
            - 8093:80
